/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/allprojects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Projects */
        get: operations["get_all_projects_api_allprojects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/setup_state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Setup State */
        get: operations["get_project_setup_state_api_project_setup_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Name */
        get: operations["get_project_name_api_project_name_get"];
        /** Put Project Name */
        put: operations["put_project_name_api_project_name_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Paths */
        get: operations["get_project_paths_api_project_paths_get"];
        /** Update Project Paths */
        put: operations["update_project_paths_api_project_paths_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Metadata */
        get: operations["get_project_metadata_api_project_metadata_get"];
        /** Put Project Metadata */
        put: operations["put_project_metadata_api_project_metadata_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/perf/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Perf Location */
        get: operations["get_perf_location_api_project_perf_location_get"];
        /** Put Perf Location */
        put: operations["put_perf_location_api_project_perf_location_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/perf/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Perfdetect */
        post: operations["post_perfdetect_api_project_perf_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/scanarea": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scanarea
         * @description Get the camera Scanarea, the area that defines the film frame content to be used.
         *     All values are normalized (ref_delta: between -1 and 1, size: between 0 and 1) and
         *     independent of the select camera image resolution.
         */
        get: operations["get_scanarea_api_project_scanarea_get"];
        /**
         * Put Scanarea
         * @description Set the ScanArea, the area that defines the film frame content to be used.
         *     All values are normalized (between 0 and 1) to be independent of the select camera image resolution.
         *         - ref_delta: The delta between the Perforation reference point and the top left point of the scan area.
         *         - size: The size of the scan area.
         */
        put: operations["put_scanarea_api_project_scanarea_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Error */
        Error: {
            /**
             * Msg
             * @default
             */
            msg: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OffsetPoint */
        OffsetPoint: {
            /**
             * Dx
             * @default 0
             */
            dx: number;
            /**
             * Dy
             * @default 0
             */
            dy: number;
        };
        /** PerforationLocation */
        PerforationLocation: {
            /**
             * Top Edge
             * @default 0
             */
            top_edge: number;
            /**
             * Bottom Edge
             * @default 0
             */
            bottom_edge: number;
            /**
             * Inner Edge
             * @default 0
             */
            inner_edge: number;
            /**
             * Outer Edge
             * @default 0
             */
            outer_edge: number;
            /** @description Reference point for the scan area */
            reference: components["schemas"]["Point"];
        };
        /** Point */
        Point: {
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
        };
        /** ProjectMetaData */
        ProjectMetaData: {
            /**
             * Creation Date
             * Format: date-time
             * @default 2025-03-26T23:58:22.518667
             */
            creation_date: string;
            /**
             * Film Date
             * Format: date-time
             * @default 2025-03-26T23:58:22.518694
             */
            film_date: string;
            /**
             * Film Title
             * @default
             */
            film_title: string;
            /**
             * Film Description
             * @default
             */
            film_description: string;
            /**
             * Film Author
             * @default
             */
            film_author: string;
            /**
             * File Fps
             * @default 18
             */
            file_fps: number;
            /**
             * Film Tags
             * @default []
             */
            film_tags: string[];
        };
        /** ProjectName */
        ProjectName: {
            /**
             * Name
             * @default
             */
            name: string;
        };
        /** ProjectPaths */
        ProjectPaths: {
            /**
             * Scanned Images
             * @default images_raw
             */
            scanned_images: string;
            /**
             * Processed Images
             * @default images_processed
             */
            processed_images: string;
        };
        /** ProjectSetupState */
        ProjectSetupState: {
            /**
             * Scanareaset
             * @default false
             */
            scanAreaSet: boolean;
            /**
             * Perforationlocationset
             * @default false
             */
            perforationLocationSet: boolean;
            /**
             * Cameraset
             * @default false
             */
            cameraSet: boolean;
            /**
             * Whitebalanceset
             * @default false
             */
            whiteBalanceSet: boolean;
            /**
             * Pathsset
             * @default false
             */
            pathsSet: boolean;
            /**
             * Nameset
             * @default false
             */
            nameSet: boolean;
        };
        /** ScanArea */
        ScanArea: {
            /** @description delta from reference point to top left */
            ref_delta: components["schemas"]["OffsetPoint"];
            /** @description width of the scan area */
            size: components["schemas"]["Size"];
        };
        /** Size */
        Size: {
            /**
             * Width
             * @default 0
             */
            width: number;
            /**
             * Height
             * @default 0
             */
            height: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_all_projects_api_allprojects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    get_project_setup_state_api_project_setup_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSetupState"];
                };
            };
        };
    };
    get_project_name_api_project_name_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectName"];
                };
            };
        };
    };
    put_project_name_api_project_name_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectName"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectName"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_paths_api_project_paths_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPaths"];
                };
            };
        };
    };
    update_project_paths_api_project_paths_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectPaths"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPaths"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_metadata_api_project_metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMetaData"];
                };
            };
        };
    };
    put_project_metadata_api_project_metadata_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectMetaData"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMetaData"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_perf_location_api_project_perf_location_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerforationLocation"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    put_perf_location_api_project_perf_location_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PerforationLocation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerforationLocation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_perfdetect_api_project_perf_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Point"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerforationLocation"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scanarea_api_project_scanarea_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanArea"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    put_scanarea_api_project_scanarea_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanArea"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanArea"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
