import type {components} from "../tofisca_api.d.ts"; // generated by openapi-typescript

export type Point = components["schemas"]["Point"]
export type PerforationLocation = components["schemas"]["PerforationLocation"];
export type ScanArea = components["schemas"]["ScanArea"];
export type ProjectState = components["schemas"]["ProjectState"];
export type FilmData = components["schemas"]["FilmData-Input"];
export type FilmFormat = components["schemas"]["FilmFormat"];
export type FilmSpecKey = components["schemas"]["FilmSpecKey"];
export type ProjectPathEntry = components["schemas"]["ProjectPathEntry"];

export type APIInvalidData = components["schemas"]["APIInvalidDataError"];
export type APINoActiveProject = components["schemas"]["APINoActiveProject"]
export type APIObjectNotFound = components["schemas"]["APIObjectNotFoundError"];
export type APIProjectAlreadyExists = components["schemas"]["APIProjectAlreadyExists"];
export type APIProjectDoesNotExist = components["schemas"]["APIProjectDoesNotExist"];
export type APiError =
    APIInvalidData |
    APINoActiveProject |
    APIObjectNotFound |
    APIProjectAlreadyExists |
    APIProjectDoesNotExist
    ;

export interface Rect {
    top: number;
    bottom: number;
    left: number;
    right: number;
}


export interface Size {
    width: number;
    height: number;
}

/**
 * A normal Point, but the coordinates are normalized to be between 0 and 1.
 * This is useful for working with images and canvases where the size of the
 * element in the dom does not necessarily equate to the size of the
 * underlying image data.
 */
export type NormalizedPoint = Point


