import type {components} from "../tofisca_api.d.ts"; // generated by openapi-typescript

export type Error = components["schemas"]["Error"];
export type Point = components["schemas"]["Point"]
export type PerforationLocation = components["schemas"]["PerforationLocation"];
export type ScanArea = components["schemas"]["ScanArea"];
export type ProjectSetupState = components["schemas"]["ProjectSetupState"];
export type FilmData = components["schemas"]["FilmData"];
export type ProjectPaths = components["schemas"]["ProjectPaths"];


export interface Rect {
    top: number;
    bottom: number;
    left: number;
    right: number;
}


export interface Size {
    width: number;
    height: number;
}

/**
 * A normal Point, but the coordinates are normalized to be between 0 and 1.
 * This is useful for working with images and canvases where the size of the
 * element in the dom does not necessarily equate to the size of the
 * underlying image data.
 */
export type NormalizedPoint = Point


